modules: add go.mod and go.sum
globalsign/mgo pull request #289
Opened 2018-10-24 07:15 UTC by jerome-laforge

#283 In order to support Go modules, add go.mod and go.sum

2018-11-09 10:04 UTC, szank approved these changes

2018-11-09 14:16 UTC, csucu approved these changes

2018-11-09 14:26 UTC, domodwyer commented
Hi @jerome-laforge 

Would you mind targeting `development` - the mod support will land in the next release that way, and keeps the branches in-sync.

Dom

2018-11-09 14:27 UTC, domodwyer requested changes
Targets `master`

2018-11-10 19:08 UTC, jerome-laforge commented
ok, thx for review, I have just create #296

2018-11-12 11:35 UTC, closed without merging